In [3]:
# matrix multiplication

import numpy as np

def fib(n):
    M = np.matrix([[0, 1], [1, 1]])
    vec = np.array([[0], [1]])

    return np.matmul(M ** n, vec)[0]

fib(8)

matrix([[21]])

In [4]:
display(np.matrix([[0, 1], [1, 1]]))

matrix([[0, 1],
        [1, 1]])

In [5]:
display(np.matrix([[0, 1], [1, 1]]) ** 2)

matrix([[1, 1],
        [1, 2]])

In [7]:
display(np.matrix([[0, 1], [1, 1]]) ** 2 * np.array([[0], [1]]))

matrix([[1],
        [2]])